export const queryKeys = {
  employees: {
    all: ['employees'] as const,
    lists: () => [...queryKeys.employees.all, 'list'] as const,
    list: (filters?: Record<string, string>) => [...queryKeys.employees.lists(), filters] as const,
    details: () => [...queryKeys.employees.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.employees.details(), id] as const,
  },
  timeLogs: {
    all: ['timeLogs'] as const,
    lists: () => [...queryKeys.timeLogs.all, 'list'] as const,
    list: (filters?: Record<string, string>) => [...queryKeys.timeLogs.lists(), filters] as const,
  },
  leaves: {
    all: ['leaves'] as const,
    lists: () => [...queryKeys.leaves.all, 'list'] as const,
    list: (filters?: Record<string, string>) => [...queryKeys.leaves.lists(), filters] as const,
    details: () => [...queryKeys.leaves.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.leaves.details(), id] as const,
  },
  overtime: {
    all: ['overtime'] as const,
    lists: () => [...queryKeys.overtime.all, 'list'] as const,
    list: (filters?: Record<string, string>) => [...queryKeys.overtime.lists(), filters] as const,
  },
  payroll: {
    all: ['payroll'] as const,
    lists: () => [...queryKeys.payroll.all, 'list'] as const,
    list: (filters?: Record<string, string>) => [...queryKeys.payroll.lists(), filters] as const,
  },
  advances: {
    all: ['advances'] as const,
    lists: () => [...queryKeys.advances.all, 'list'] as const,
    list: (filters?: Record<string, string>) => [...queryKeys.advances.lists(), filters] as const,
    details: () => [...queryKeys.advances.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.advances.details(), id] as const,
    summary: (employeeId: string) => [...queryKeys.advances.all, 'summary', employeeId] as const,
  },
  holidays: {
    all: ['holidays'] as const,
    lists: () => [...queryKeys.holidays.all, 'list'] as const,
    list: (year?: number) => [...queryKeys.holidays.lists(), year] as const,
  },
  schedules: {
    all: ['schedules'] as const,
    lists: () => [...queryKeys.schedules.all, 'list'] as const,
    list: (filters?: Record<string, string>) => [...queryKeys.schedules.lists(), filters] as const,
  },
  users: {
    all: ['users'] as const,
    lists: () => [...queryKeys.users.all, 'list'] as const,
    list: () => [...queryKeys.users.lists()] as const,
  },
  accounting: {
    accounts: {
      all: ['accounting', 'accounts'] as const,
      lists: () => [...queryKeys.accounting.accounts.all, 'list'] as const,
      list: (filters?: Record<string, string>) => [...queryKeys.accounting.accounts.lists(), filters] as const,
    },
    journal: {
      all: ['accounting', 'journal'] as const,
      lists: () => [...queryKeys.accounting.journal.all, 'list'] as const,
      list: (filters?: Record<string, string>) => [...queryKeys.accounting.journal.lists(), filters] as const,
    },
    expenses: {
      all: ['accounting', 'expenses'] as const,
      lists: () => [...queryKeys.accounting.expenses.all, 'list'] as const,
      list: (filters?: Record<string, string>) => [...queryKeys.accounting.expenses.lists(), filters] as const,
    },
    purchases: {
      all: ['accounting', 'purchases'] as const,
      lists: () => [...queryKeys.accounting.purchases.all, 'list'] as const,
      list: (filters?: Record<string, string>) => [...queryKeys.accounting.purchases.lists(), filters] as const,
    },
    sales: {
      all: ['accounting', 'sales'] as const,
      lists: () => [...queryKeys.accounting.sales.all, 'list'] as const,
      list: (filters?: Record<string, string>) => [...queryKeys.accounting.sales.lists(), filters] as const,
    },
    vendors: {
      all: ['accounting', 'vendors'] as const,
      lists: () => [...queryKeys.accounting.vendors.all, 'list'] as const,
      list: (filters?: Record<string, string>) => [...queryKeys.accounting.vendors.lists(), filters] as const,
    },
    customers: {
      all: ['accounting', 'customers'] as const,
      lists: () => [...queryKeys.accounting.customers.all, 'list'] as const,
      list: (filters?: Record<string, string>) => [...queryKeys.accounting.customers.lists(), filters] as const,
    },
    reports: {
      all: ['accounting', 'reports'] as const,
      data: (type: string, filters?: Record<string, string>) => [...queryKeys.accounting.reports.all, type, filters] as const,
    },
    subsidiaryLedgers: {
      all: ['accounting', 'subsidiary-ledgers'] as const,
      lists: () => [...queryKeys.accounting.subsidiaryLedgers.all, 'list'] as const,
      list: (filters?: Record<string, string>) => [...queryKeys.accounting.subsidiaryLedgers.lists(), filters] as const,
    },
    reconciliation: {
      all: ['accounting', 'reconciliation'] as const,
      data: (filters?: Record<string, string>) => [...queryKeys.accounting.reconciliation.all, filters] as const,
    },
    pettyCash: {
      all: ['accounting', 'petty-cash'] as const,
      lists: () => [...queryKeys.accounting.pettyCash.all, 'list'] as const,
      list: (filters?: Record<string, string>) => [...queryKeys.accounting.pettyCash.lists(), filters] as const,
    },
  },
  assets: {
    all: ['assets'] as const,
    lists: () => [...queryKeys.assets.all, 'list'] as const,
    list: (filters?: Record<string, string>) => [...queryKeys.assets.lists(), filters] as const,
    details: () => [...queryKeys.assets.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.assets.details(), id] as const,
    categories: {
      all: ['assets', 'categories'] as const,
      lists: () => [...queryKeys.assets.categories.all, 'list'] as const,
      list: () => [...queryKeys.assets.categories.lists()] as const,
    },
    transactions: {
      all: ['assets', 'transactions'] as const,
      lists: () => [...queryKeys.assets.transactions.all, 'list'] as const,
      list: (filters?: Record<string, string>) => [...queryKeys.assets.transactions.lists(), filters] as const,
    },
  },
  branches: {
    all: ['branches'] as const,
    lists: () => [...queryKeys.branches.all, 'list'] as const,
    list: () => [...queryKeys.branches.lists()] as const,
  },
  officeLocations: {
    all: ['officeLocations'] as const,
    lists: () => [...queryKeys.officeLocations.all, 'list'] as const,
    list: () => [...queryKeys.officeLocations.lists()] as const,
  },
  dashboard: {
    all: ['dashboard'] as const,
    stats: (filters?: Record<string, string>) => [...queryKeys.dashboard.all, 'stats', filters] as const,
  },
  cusa: {
    all: ['cusa'] as const,
    units: () => [...queryKeys.cusa.all, 'units'] as const,
    unit: (id: string) => [...queryKeys.cusa.units(), id] as const,
    rates: () => [...queryKeys.cusa.all, 'rates'] as const,
    rate: (id: string) => [...queryKeys.cusa.rates(), id] as const,
    bills: () => [...queryKeys.cusa.all, 'bills'] as const,
    bill: (id: string) => [...queryKeys.cusa.bills(), id] as const,
    payments: () => [...queryKeys.cusa.all, 'payments'] as const,
    payment: (id: string) => [...queryKeys.cusa.payments(), id] as const,
    dashboard: () => [...queryKeys.cusa.all, 'dashboard'] as const,
    overdue: () => [...queryKeys.cusa.all, 'overdue'] as const,
  },
  water: {
    all: ['water'] as const,
    tenants: {
      all: ['water', 'tenants'] as const,
      lists: () => [...queryKeys.water.tenants.all, 'list'] as const,
      list: (filters?: Record<string, string>) => [...queryKeys.water.tenants.lists(), filters] as const,
      details: () => [...queryKeys.water.tenants.all, 'detail'] as const,
      detail: (id: string) => [...queryKeys.water.tenants.details(), id] as const,
    },
    meters: {
      all: ['water', 'meters'] as const,
      lists: () => [...queryKeys.water.meters.all, 'list'] as const,
      list: (filters?: Record<string, string>) => [...queryKeys.water.meters.lists(), filters] as const,
      details: () => [...queryKeys.water.meters.all, 'detail'] as const,
      detail: (id: string) => [...queryKeys.water.meters.details(), id] as const,
    },
    readings: {
      all: ['water', 'readings'] as const,
      lists: () => [...queryKeys.water.readings.all, 'list'] as const,
      list: (filters?: Record<string, string>) => [...queryKeys.water.readings.lists(), filters] as const,
    },
    rates: {
      all: ['water', 'rates'] as const,
      lists: () => [...queryKeys.water.rates.all, 'list'] as const,
      list: (filters?: Record<string, string>) => [...queryKeys.water.rates.lists(), filters] as const,
      details: () => [...queryKeys.water.rates.all, 'detail'] as const,
      detail: (id: string) => [...queryKeys.water.rates.details(), id] as const,
    },
    bills: {
      all: ['water', 'bills'] as const,
      lists: () => [...queryKeys.water.bills.all, 'list'] as const,
      list: (filters?: Record<string, string>) => [...queryKeys.water.bills.lists(), filters] as const,
      details: () => [...queryKeys.water.bills.all, 'detail'] as const,
      detail: (id: string) => [...queryKeys.water.bills.details(), id] as const,
    },
    payments: {
      all: ['water', 'payments'] as const,
      lists: () => [...queryKeys.water.payments.all, 'list'] as const,
      list: (filters?: Record<string, string>) => [...queryKeys.water.payments.lists(), filters] as const,
    },
  },
}
